"""
@crontab: 00,30 * * * * cd ${BASE_PATH} && python -m finance.news_ai_explain.py 2>&1 | tee -a news_ai_explain.log
"""

from datetime import datetime, timedelta
from zoneinfo import ZoneInfo
import json, sys

from dotenv import load_dotenv, dotenv_values
import requests
import openai

from pyutils.notify_util import Feishu, Pushme
from pyutils.date_util import now_time, now


def get_start_end_time():
    nowtime = now_time()
    now_hm = nowtime.strftime('%H:%M')
    dt = nowtime.strftime('%Y-%m-%d')
    dt_1 = (nowtime - timedelta(days=1)).strftime('%Y-%m-%d')

    map_dict = {
        "09:30": (f"{dt} 00:00:00", f"{dt} 09:30:00"),
        "11:30": (f"{dt} 09:30:00", f"{dt} 11:30:00"),
        "13:00": (f"{dt} 11:30:00", f"{dt} 13:00:00"),
        "15:00": (f"{dt} 13:00:00", f"{dt} 15:00:00"),
        "18:00": (f"{dt} 15:00:00", f"{dt} 18:00:00"),
        "21:00": (f"{dt} 18:00:00", f"{dt} 21:00:00"),
        "24:00": (f"{dt_1} 21:00:00", f"{dt_1} 24:00:00"),
        "00:00": (f"{dt_1} 21:00:00", f"{dt_1} 24:00:00"),
    }
    return map_dict[now_hm] if now_hm in map_dict else ((nowtime-timedelta(hours=3)).strftime('%Y-%m-%d %H:%M:%S'), '9999-12-31 23:59:59')


if __name__ == '__main__':
    config = dotenv_values(".env")
    news_api = 'https://newsapi.eastmoney.com/kuaixun/v1/getlist_102_ajaxResult_100_1_.html'  # 最新100条
    ua_headers = {'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.5 Mobile/15E148 Safari/604.1 Edg/143.0.0.0'}

    # 新闻时间范围，避免多次运行重复
    start_time, end_time = get_start_end_time()
    now_str = now('%Y-%m-%d %H:%M')
    if '9999' in end_time and 'onlytime' in ''.join(sys.argv):
        sys.exit(0)

    # 抓取东财7x24小时的最新N条，并按时间过滤
    resp = requests.get(news_api, headers=ua_headers)
    data = json.loads(resp.text.split('=', 1)[-1])
    LivesList = data['LivesList']; print(f'len(LivesList) = {len(LivesList)}')

    filter_LivesList = [{key:one[key] for key in ('showtime','title','digest')} for one in LivesList if start_time<=one['showtime']<end_time]  # url_unique
    news_json = json.dumps(filter_LivesList, ensure_ascii=False, separators=(',',':'));print(news_json)  # 紧密输出
    real_start, real_end = min([x['showtime'] for x in filter_LivesList]), max([x['showtime'] for x in filter_LivesList])


    # AI总结
    client = openai.OpenAI(api_key=config['OPENAI_API_KEY'], base_url=config['OPENAI_BASE_URL'])
    completion = client.chat.completions.create(
        #以此处为例，请确保替换为你实际在 build.nvidia.com 选择的模型名称
        model=config['OPENAI_MODEL_ID'],
        messages=[
            {"role": "system", "content": "你是财经新闻解读和个人投资建议助手。阅读下面内容，分类新闻，按重要性排序，并解读每个新闻的内在逻辑、市场影响和对个人投资者的投资影响"},
            {"role": "user", "content": news_json}
        ],
        temperature=0.7,
        top_p=0.95,
        max_tokens=65535,
        stream=False # 开启流式输出
    )
    news_ai_explain = completion.choices[0].message.content; print(news_ai_explain); print(completion.usage)

    # 飞书通知
    title = f"财经新闻解读({now_str})"
    footer = f'🤖 Generated by AI\n{start_time} ~ {end_time}\n{real_start} ~ {real_end}'

    try:
        Feishu(config['FEISHU_WEBHOOK_TOKEN']).send_markdown(title, news_ai_explain, footer=footer)
    finally:
        Pushme(config['PUSHME_PUSH_KEY']).send_markdown('[#7x24小时财经新闻!📜]'+title, news_ai_explain)

